export const PDF_ACTIONS = {
  SET_FILES: 'SET_FILES',
  ADD_FILE: 'ADD_FILE',
  REMOVE_FILE: 'REMOVE_FILE',
  CLEAR_FILES: 'CLEAR_FILES',
  SET_PROCESSED_FILE: 'SET_PROCESSED_FILE',
  SET_PROCESSING: 'SET_PROCESSING',
  SET_PROGRESS: 'SET_PROGRESS',
  ADD_TO_HISTORY: 'ADD_TO_HISTORY',
  SET_ERROR: 'SET_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
};
