services:
  api:
    volumes:
      - ./server:/app
      - /app/node_modules
      - shared-files:/app/shared
    command: sh -c "mkdir -p /app/shared/temp/uploads /app/shared/public/processed \
      && chown -R 1000:1000 /app/shared \
      && chmod -R 755 /app/shared \
      && npm run dev:server"
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8080/api/v1/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  worker:
    volumes:
      - ./server:/app
      - /app/node_modules
      - shared-files:/app/shared
    command: sh -c "mkdir -p /app/shared/temp/uploads /app/shared/public/processed \
      && chown -R 1000:1000 /app/shared \
      && chmod -R 755 /app/shared \
      && npm run dev:worker"
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

