FROM node:20-bookworm
WORKDIR /app

ARG UID=1000
ARG GID=1000

RUN apt-get update && apt-get install -y --no-install-recommends \
  qpdf \
  libreoffice \
  poppler-utils \
  && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install
COPY src ./src

ENV NODE_ENV=production

RUN \
    if [ "${GID}" != "1000" ]; then groupmod -g ${GID} node; fi && \
    if [ "${UID}" != "1000" ]; then usermod -u ${UID} node; fi


