FROM node:20-alpine AS base
WORKDIR /app
COPY package*.json ./
RUN npm install

FROM node:20-alpine
WORKDIR /app

ARG UID=1000
ARG GID=1000

COPY --from=base /app/node_modules ./node_modules
COPY src ./src

RUN apk add --no-cache shadow

RUN \
    if [ "${GID}" != "1000" ]; then groupmod -g ${GID} node; fi && \
    if [ "${UID}" != "1000" ]; then usermod -u ${UID} node; fi

ENV NODE_ENV=production
ENV PORT=8080
EXPOSE 8080
